version: "3"
services:
  nest-api:
    build:
      context: .
      target: install-dependencies
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - ./db:/app/db
    env_file:
      - .env
    ports:
      - "3000:3000"