name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-app:
    name: 'CI'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Check Code-Styling
        run: |
          yarn lint
          yarn prettier

      - name: Run Unit Tests
        run: yarn test

      - name: Run Build
        run: yarn build

      - name: Build Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username maugarbru --password-stdin
          docker build -t maugarbru/nest-api-devops .
          docker push maugarbru/nest-api-devops