name: Main CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: 'CI/CD'
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      PORT: ${{ vars.PORT }}
      NODE_ENV: ${{vars.NODE_ENV}}
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
        
      - name: Install serverless globally
        run: npm install -g serverless

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Check Code-Styling
        run: |
          yarn lint
          yarn prettier

      - name: Run Unit Tests
        run: yarn test

      - name: Run Build
        run: yarn build

      # - name: Deploy lambda function
      #   run: sls deploy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}