name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-app:
    name: 'CI/CD'
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      PORT: ${{ vars.PORT }}
      NODE_ENV: ${{vars.NODE_ENV}}
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Check Code-Styling
        run: |
          yarn lint
          yarn prettier

      - name: Run Unit Tests
        run: yarn test

      - name: Run Build
        run: yarn build